# Generated by Django 4.2.2 on 2024-07-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoH.devicetype', verbose_name='DeviceType'),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='data',
            field=models.CharField(max_length=200, null=True, verbose_name='Data'),
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(max_length=200, null=True, verbose_name='Date')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoH.device', verbose_name='Device')),
            ],
        ),
    ]
