# Generated by Django 4.2.2 on 2023-09-01 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.categories', verbose_name='Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldValue', models.CharField(max_length=25, null=True, verbose_name='Sku')),
                ('newValue', models.CharField(max_length=25, null=True, verbose_name='Sku')),
                ('dateСhange', models.DateTimeField(verbose_name='DateСhange')),
            ],
        ),
        migrations.CreateModel(
            name='FieldСhange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('sku', models.CharField(max_length=25, null=True, verbose_name='Sku')),
                ('images', models.JSONField(max_length=200, null=True, verbose_name='Images')),
                ('comparisonName', models.CharField(max_length=12, null=True, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.categories', verbose_name='Categories')),
                ('changes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.change', verbose_name='Changes')),
            ],
        ),
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('param', models.CharField(max_length=200, verbose_name='Param')),
            ],
        ),
        migrations.CreateModel(
            name='Sourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.warehouse', verbose_name='Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('descriptionSeparator', models.CharField(max_length=10, verbose_name='DescriptionSeparator')),
                ('itemDesc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.itemdescription', verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='change',
            name='fieldСhange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.fieldсhange', verbose_name='FieldСhange'),
        ),
        migrations.AddField(
            model_name='change',
            name='itemChange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='change',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.sourse', verbose_name='Sourse'),
        ),
        migrations.AddField(
            model_name='change',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
