# Generated by Django 4.2.2 on 2023-09-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemPrAppApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comparisonName',
            field=models.JSONField(null=True, verbose_name='ComparisonName'),
        ),
    ]
