# Generated by Django 4.2.2 on 2023-09-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemPrAppApi', '0002_alter_item_comparisonname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='comparisonName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.item', verbose_name='Item')),
            ],
        ),
    ]
