# Generated by Django 4.2.2 on 2023-09-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemPrAppApi', '0003_remove_item_comparisonname_remove_item_images_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisonname',
            old_name='name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='uri',
        ),
    ]
