# Generated by Django 4.2.2 on 2023-09-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemPrAppApi', '0004_rename_name_comparisonname_cname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonname',
            name='cname',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='comparisonname',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.item', verbose_name='Item'),
        ),
    ]
