# Generated by Django 4.2.2 on 2023-09-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemPrAppApi', '0005_alter_comparisonname_cname_alter_comparisonname_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='manufactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.manufactor', verbose_name='Manufactor'),
        ),
        migrations.AddField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='ItemPrAppApi.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.categories', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='comparisonname',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemComparisonName', to='ItemPrAppApi.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='details',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ItemPrAppApi.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ItemPrAppApi.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.warehouse', verbose_name='Warehouse'),
        ),
    ]
