# Generated by Django 4.2.2 on 2023-09-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemPrAppApi', '0006_item_manufactor_stock_item_alter_categories_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='newValue',
            field=models.CharField(max_length=25, null=True, verbose_name='newValue'),
        ),
        migrations.AlterField(
            model_name='change',
            name='oldValue',
            field=models.CharField(max_length=25, null=True, verbose_name='oldValue'),
        ),
        migrations.AlterField(
            model_name='itemdescription',
            name='description',
            field=models.CharField(max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='itemdescription',
            name='descriptionSeparator',
            field=models.CharField(max_length=10, null=True, verbose_name='DescriptionSeparator'),
        ),
        migrations.AlterField(
            model_name='itemdescription',
            name='itemDesc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemPrAppApi.item', verbose_name='Item'),
        ),
    ]
