# Generated by Django 4.2.2 on 2023-06-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_newtable_la'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewTable',
            new_name='Atable',
        ),
        migrations.AlterModelOptions(
            name='atable',
            options={'verbose_name': 'Таблица'},
        ),
    ]
