# Generated by Django 4.2.2 on 2023-06-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_newtable_atable_alter_atable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atable',
            options={'verbose_name': 'Таблица', 'verbose_name_plural': 'Таблицы'},
        ),
    ]
