# Generated by Django 4.2.2 on 2023-07-05 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_btable_alter_atable_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atable',
            name='anons',
            field=models.CharField(max_length=250, null=True, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='atable',
            name='date',
            field=models.DateTimeField(null=datetime.date(2023, 7, 5), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='atable',
            name='full_text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='atable',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
