# Generated by Django 4.2.2 on 2023-08-08 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_atable_options_alter_btable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atable',
            name='date',
            field=models.DateTimeField(null=datetime.date(2023, 8, 8), verbose_name='Дата'),
        ),
    ]
