# Generated by Django 4.2.2 on 2023-09-04 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_atable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atable',
            name='date',
            field=models.DateTimeField(null=datetime.date(2023, 9, 4), verbose_name='Дата'),
        ),
    ]
