# Generated by Django 4.2.2 on 2023-11-21 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_atable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atable',
            name='date',
            field=models.DateTimeField(null=datetime.date(2023, 11, 21), verbose_name='Дата'),
        ),
    ]
