# Generated by Django 4.2.2 on 2024-05-24 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_atable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atable',
            name='date',
            field=models.DateTimeField(null=datetime.date(2024, 5, 24), verbose_name='Дата'),
        ),
    ]
