# Generated by Django 4.2.2 on 2024-07-23 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_atable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atable',
            name='date',
            field=models.DateTimeField(null=datetime.date(2024, 7, 23), verbose_name='Дата'),
        ),
    ]
