//// <auto-generated />
//using EntityFrameworkCore.Jet.Metadata;
//using MGSol.Base.EntityFrameworkCoreJetTest5;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace MGSol.Migrations
//{
//    [DbContext(typeof(ApplicationContext))]
//    [Migration("20221021151634_1")]
//    partial class _1
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("Relational:MaxIdentifierLength", 64)
//                .HasAnnotation("ProductVersion", "5.0.14")
//                .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("MGSol.Base.EntityFrameworkCoreJetTest5.Company", b =>
//                {
//                    b.Property<int>("ID")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("integer");

//                    b.Property<string>("CompanyName")
//                        .HasColumnType("longchar");

//                    b.HasKey("ID");

//                    b.ToTable("Companies");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
