# Generated by Django 4.2.2 on 2023-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostingAccounting', '0002_item_description_item_url_alter_item_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='annotation',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Номер'),
        ),
    ]
