# Generated by Django 4.2.2 on 2023-08-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='orderItems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.items', verbose_name='Позиции'),
        ),
    ]
