# Generated by Django 4.2.2 on 2023-08-09 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0004_alter_orders_orderitems_alter_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderItems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.items', verbose_name='Позиции'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
