# Generated by Django 4.2.2 on 2023-08-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_orders_orderitems_alter_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orderItems',
        ),
        migrations.AddField(
            model_name='items',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.orders', verbose_name='Позиции'),
        ),
    ]
