# Generated by Django 4.2.2 on 2023-08-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_remove_orders_orderitems_items_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderItems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.items', verbose_name='Позиции'),
        ),
        migrations.AlterField(
            model_name='items',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.orders', verbose_name='Заказ'),
        ),
    ]
