# Generated by Django 4.2.2 on 2023-08-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_remove_orders_orderitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('storeApiId', models.CharField(max_length=50, verbose_name='ID')),
                ('storeINN', models.CharField(max_length=50, verbose_name='ИНН')),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='Api.orders', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orders',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.store', verbose_name='Магазин'),
        ),
    ]
